"""empty message

Revision ID: 3af62617ee4b
Revises: 429fbfe291d1
Create Date: 2021-05-17 17:25:16.496238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af62617ee4b'
down_revision = '429fbfe291d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_token', sa.Column('access_token_revoked_at', sa.Integer(), nullable=False))
    op.add_column('oauth2_token', sa.Column('refresh_token_revoked_at', sa.Integer(), nullable=False))
    op.drop_column('oauth2_token', 'revoked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_token', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('oauth2_token', 'refresh_token_revoked_at')
    op.drop_column('oauth2_token', 'access_token_revoked_at')
    # ### end Alembic commands ###
